import Head from 'next/head';
import React from 'react';
import SignUp from '../../components/Auth/SignUp';

const signup = () => {
  return (
    <div className="container">
      <Head>
        <title>Global Aloha | Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignUp />
    </div>
  );
};

export default signup;
